config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  root to: 'user/home#top'

  namespace :user do
    get "home/top" => "home#top"
    get "home/about" => "home#about"
    resources :inquiry, only: [:index, :create]
    get  'inquiry/confirm' => 'inquiry#confirm'   
    get  'inquiry/thanks'  => 'inquiry#thanks'
    resources :users, only: [:show, :edit, :update]
    get "users/follow_index/:id" => "users#follow_index",as: "users_follow_index"
    get "users/follower_index/:id" => "users#follower_index",as: "users_follower_index"
    resources :relationships, only: [:create, :destroy]
    resources :messages, only: :create
    resources :rooms, only: [:create,:show]
    resources :spotify, only: :index
    get "spotify/artist_show/:id" => "spotify#artist_show" , as: "spotify_artist_show"
    get "spotify/album_show/:id" => "spotify#album_show" , as: "spotify_album_show"
    get "spotify/song_show/:id" => "spotify#song_show" , as: "spotify_song_show"
    get "spotify/new_releases" => "spotify#new_releases", as: "spotify_new_releases"
    get "spotify/charged_ups" => "spotify#charged_ups", as: "spotify_charged_ups"
    resources :artist_comments, only: [:create, :destroy, :update]
    resources :artist_ratings, only: [:create, :update]
    resources :album_comments, only: [:create, :destroy, :update]
    resources :album_ratings, only: [:create, :update]
    resources :song_comments, only: [:create, :destroy, :update]
    resources :song_ratings, only: [:create, :update]
    resources :song_favorites, only: [:index, :create, :destroy]
    resources :song_impressions, only: [:index]
    resources :notifications, only: :index
    resources :browsing_history, only: :index
  end

end

app/controllers/user/album_comments_controller.rb
class User::AlbumCommentsController < ApplicationController

  before_action :login_user_present?
  before_action :correct_comment_user, only: [:update, :destroy]
  before_action :set_page, except: [:destroy]

  def create
    @album_comment = current_user.album_comments.new(album_comment_params)
    @album_comment.album_id = params[:album_comment][:album_id]
    if @album_comment.save 
      redirect_to user_spotify_album_show_path(@album_comment.album_id, page: @page)
    else
      set_error_variables(@album_comment.album_id, params[:page])
    end
  end

  def update
    if @comment.update(album_comment_params)
      redirect_to user_spotify_album_show_path(@comment.album_id, page: @page)
    else
      @album_comment = AlbumComment.new
      set_error_variables(@comment.album_id, params[:page])
    end
  end

  def destroy
    @comment.destroy
    redirect_to user_spotify_album_show_path(@comment.album_id)
  end

  def set_error_variables(album_id, page_params)
    @album = RSpotify::Album.find(album_id)
    @songs = @album.tracks
    @album_comments = AlbumComment.where(album_id: @album.id).order("id DESC").page(page_params).per(5)
    if user_signed_in?
      @album_rating = current_user.album_ratings.find_by(album_id: @album.id)
      @new_album_rating = current_user.album_ratings.new
    end
    @error = true
    render "user/spotify/album_show"
  end

  private

  def album_comment_params
    params.require(:album_comment).permit(:comment)
  end
  

end

app/controllers/user/album_ratings_controller.rb
class User::AlbumRatingsController < ApplicationController

  before_action :correct_user, only: [:update]

  def create
    @album_rating = current_user.album_ratings.new(album_rating_params)
    @album_rating.album_id = params[:album_rating][:album_id]
    redirect_back(fallback_location: root_path) unless @album_rating.save
  end

  def update
    @album_rating = AlbumRating.find(params[:id])
    redirect_back(fallback_location: root_path) unless @album_rating.update(album_rating_params)
  end


  private

  def album_rating_params
    params.require(:album_rating).permit(:rate, :album_id)
  end

  def correct_user
    rating = AlbumRating.find(params[:id])
    redirect_to root_path unless current_user == rating.user
  end

end

app/controllers/user/artist_comments_controller.rb
class User::ArtistCommentsController < ApplicationController

  before_action :login_user_present?
  before_action :correct_comment_user, only: [:update, :destroy]
  before_action :set_page, except: [:destroy]

  def create
    @artist_comment = current_user.artist_comments.new(artist_comment_params)
    @artist_comment.artist_id = params[:artist_comment][:artist_id]
    if @artist_comment.save 
      redirect_to user_spotify_artist_show_path(@artist_comment.artist_id, page: @page)
    else
      set_error_variables(params[:artist_comment][:artist_id], params[:page])
    end
  end

  def update
    if @comment.update(artist_comment_params)
      redirect_to user_spotify_artist_show_path(@comment.artist_id, page: @page)
    else
      @artist_comment = ArtistComment.new
      set_error_variables(@comment.artist_id, params[:page])
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to user_spotify_artist_show_path(@comment.artist_id)
  end

  def set_error_variables(artist_id, page_params)
    @artist = RSpotify::Artist.find(artist_id)
    @albums = @artist.albums
    @artist_comments = ArtistComment.where(artist_id: @artist.id).order("id DESC").page(page_params).per(5)
    @error = true
    render "user/spotify/artist_show"
  end

  private

  def artist_comment_params
    params.require(:artist_comment).permit(:comment)
  end

end

app/controllers/user/artist_ratings_controller.rb
class User::ArtistRatingsController < ApplicationController

  before_action :correct_user, only: [:update]

  def create
    @artist_rating = current_user.artist_ratings.new(artist_rating_params)
    @artist_rating.artist_id = params[:artist_rating][:artist_id]
    redirect_back(fallback_location: root_path) unless @artist_rating.save
  end

  def update
    @artist_rating = ArtistRating.find(params[:id])
    redirect_back(fallback_location: root_path) unless @artist_rating.update(artist_rating_params)
  end


  private

  def artist_rating_params
    params.require(:artist_rating).permit(:rate, :artist_id)
  end

  def correct_user
    rating = ArtistRating.find(params[:id])
    redirect_to root_path unless current_user == rating.user
  end

end

app/controllers/user/browsing_history_controller.rb
class User::BrowsingHistoryController < ApplicationController

  def index
    @songs = SongImpression.where(user_id: current_user.id).order(updated_at: :desc).pluck(:song_id).uniq
  end

end

app/controllers/user/home_controller.rb
class User::HomeController < ApplicationController

  def top
    @song_comments = current_user.song_comments.order("id DESC").select(:song_id).distinct.limit(3) if current_user.present?
    @new_releases =  RSpotify::Album.new_releases
    @new_releases_in_jp =  RSpotify::Album.new_releases(country: 'JP')
    @charged_up = SongComment.group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
  end

  def about
    
  end

end

app/controllers/user/inquiry_controller.rb
class User::InquiryController < ApplicationController

  before_action :authenticate_user!

  def index
    @inquiry = (params[:inquiry] ? Inquiry.new(inquiry_params) : Inquiry.new )
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    render :index if @inquiry.invalid?
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      InquiryMailer.received_email(@inquiry).deliver
      InquiryMailer.confirm_email(@inquiry).deliver
      redirect_to user_inquiry_thanks_path
    else
      redirect_to user_inquiry_index_path
    end
  end

  def thanks
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
  
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  
  before_action :authenticate_user!

  def create

  end

end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController

  before_action :authenticate_user!

  def index
    #current_userの投稿に紐づいた通知一覧
    @notifications = current_user.passive_notifications.includes(:visiter)
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
      @notifications.where(checked: false).each do |notification|
        notification.update_attributes(checked: true)
      end
  end

end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController

  prepend_before_action :authenticate_user!
  before_action :set_user, :set_follows

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      @user.create_notification_follow!(current_user)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  private
  
  def set_user
    @user = User.find(params[:relationship][:follow_id])
  end

  def set_follows
    if params[:relationship][:index_user_id]
      @follows = User.find(params[:relationship][:index_user_id]).relationships
    end
  end

end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to user_room_path(@room.id, pair_user_id: @entry2.user_id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages.includes(:user)
      @pair_user = User.find(params[:pair_user_id])
      # フッター固定用
      @fixed_footer = true
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/user/song_comments_controller.rb
class User::SongCommentsController < ApplicationController

  before_action :login_user_present?
  before_action :correct_comment_user, only: [:update, :destroy]
  before_action :set_page, except: [:destroy]

  def create
    @song_comment = current_user.song_comments.new(song_comment_params)
    @song_comment.song_id = params[:song_comment][:song_id]
    if @song_comment.save 
      redirect_to user_spotify_song_show_path(@song_comment.song_id, page: @page)
    else
      set_error_variables(@song_comment.song_id, params[:page])
    end

  end

  def update
    if @comment.update(song_comment_params)
      redirect_to user_spotify_song_show_path(@comment.song_id, page: @page)
    else
      @song_comment = SongComment.new
      set_error_variables(@comment.song_id, params[:page])
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to user_spotify_song_show_path(@comment.song_id)
  end

  def set_error_variables(song_id, page_params)
    @song = RSpotify::Track.find(song_id)
    @album = @song.album
    @song_comments = SongComment.where(song_id: @song.id).order("id DESC").page(page_params).per(5)
    if user_signed_in?
      @song_rating = current_user.song_ratings.find_by(song_id: @song.id)
      @new_song_rating = current_user.song_ratings.new
    end
    @song_favorite = SongFavorite.find_by(user_id: current_user, song_id: @song.id)
    @error = true
    render "user/spotify/song_show"
  end

  private

  def song_comment_params
    params.require(:song_comment).permit(:comment)
  end

end

app/controllers/user/song_favorites_controller.rb
class User::SongFavoritesController < ApplicationController

  before_action :authenticate_user!, only: [:create]
  before_action :correct_user, only: [:destroy]
  before_action :set_song, only: [:create, :destroy]

  def index
    @user = User.find(params[:user_id])
    @song_favorites = @user.song_favorites
    # DM
    room_present?(@user)
  end


  def create
    new_song_favorite = current_user.song_favorites.new
    new_song_favorite.song_id = params[:song_id]
    new_song_favorite.save
    @song_favorite = SongFavorite.find_by(user_id: current_user, song_id: @song.id)
  end

  def destroy
    song_favorite = SongFavorite.find(params[:id])
    song_favorite.destroy
  end

  private

  def correct_user
    song_favorite = SongFavorite.find(params[:id])
    redirect_to root_path unless current_user == song_favorite.user
  end

  def set_song
    @song = RSpotify::Track.find(params[:song_id])
  end

end

app/controllers/user/song_impressions_controller.rb
class User::SongImpressionsController < ApplicationController

  def index
    case params[:times]
      when nil, "指定無し"
        @top_impressions = SongImpression.group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
      when "今日"
        @top_impressions = SongImpression.where(created_at: Time.zone.now.all_day).group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
        @time = "Today"
      when "１週間"
        @top_impressions = SongImpression.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day).group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
        @time = "Week"
      when "一ヶ月"
        @top_impressions = SongImpression.where(created_at: 1.month.ago.beginning_of_day..Time.zone.now.end_of_day).group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
        @time = "Month"
    end
  end
end

app/controllers/user/song_ratings_controller.rb
class User::SongRatingsController < ApplicationController

  before_action :correct_user, only: [:update]

  def create
    @song_rating = current_user.song_ratings.new(song_rating_params)
    @song_rating.song_id = params[:song_rating][:song_id]
    redirect_back(fallback_location: root_path) unless @song_rating.save
  end

  def update
    @song_rating = SongRating.find(params[:id])
    redirect_back(fallback_location: root_path) unless @song_rating.update(song_rating_params)
  end

  private

  def song_rating_params
    params.require(:song_rating).permit(:rate, :song_id)
  end

  def correct_user
    rating = SongRating.find(params[:id])
    redirect_to root_path unless current_user == rating.user
  end

end

app/controllers/user/spotify_controller.rb
class User::SpotifyController < ApplicationController

  before_action :set_page, only: [:artist_show, :album_show, :song_show]

  def index
    if params[:search].blank?
      redirect_back(fallback_location: root_path) 
    else
      @search_word = params[:search]
      @searchartists = RSpotify::Artist.search(@search_word)
      @searchalbums = RSpotify::Album.search(@search_word)
      @searchsongs = RSpotify::Track.search(@search_word)
      @artist_count = add_count(params[:artist_count])
      @album_count = add_count(params[:album_count])
      @song_count = add_count(params[:song_count])
    end
  end

  def artist_show
    @artist = RSpotify::Artist.find(params[:id])
    @albums = @artist.albums
    @artist_comment = ArtistComment.new
    @artist_comments = ArtistComment.includes(:user).where(artist_id: @artist.id).order("id DESC").page(params[:page]).per(5)
    @comment = ArtistComment.find(params[:comment_id]) if params[:comment_id].present?
  end

  def album_show
    @album = RSpotify::Album.find(params[:id])
    @songs = @album.tracks
    @album_comment = AlbumComment.new
    @album_comments = AlbumComment.includes(:user).where(album_id: @album.id).order("id DESC").page(params[:page]).per(5)
    @comment = AlbumComment.find(params[:comment_id]) if params[:comment_id].present?
    # 評価機能
    if user_signed_in?
      @album_rating = current_user.album_ratings.find_by(album_id: @album.id)
      @new_album_rating = current_user.album_ratings.new
    end
  end

  def song_show
    @song = RSpotify::Track.find(params[:id])
    @album = @song.album
    @song_comment = SongComment.new
    @song_comments = SongComment.includes(:user).where(song_id: @song.id).order("id DESC").page(params[:page]).per(5)
    @comment = SongComment.find(params[:comment_id]) if params[:comment_id].present?
    if user_signed_in?
      # 評価機能
      @song_rating = current_user.song_ratings.find_by(song_id: @song.id)
      @new_song_rating = current_user.song_ratings.new
      # PV機能
      current_user.create_song_impression(params[:id])
    end
    @song_favorite = SongFavorite.find_by(user_id: current_user, song_id: @song.id)
  end

  def new_releases
    @new_releases = new_releases_search(params[:country])
    @country_name = params[:country]
  end

  def charged_ups
    # 特定の期間内のコメントを取得して曲のIDの重複数が多い順に並び替えて取得
    @charged_up = sort_charged_ups(params[:times])[0]
    @time = sort_charged_ups(params[:times])[1]
  end
  
end

app/views/user/spotify/_song_header.html.haml
.song_header.text-center
  = link_to "Top", user_home_top_path
  = link_to "New Releases", user_spotify_new_releases_path
  = link_to "Charged Up", user_spotify_charged_ups_path
  = link_to "Top Impressions", user_song_impressions_path
  - if user_signed_in?
    = link_to "Browsing History", user_browsing_history_index_path

app/views/user/spotify/album_show.html.haml
.container
  -# アーティストリンク>アルバム名
  .row
    %h1.head_title
      = link_to "#{@album.artists.first.name}", user_spotify_artist_show_path(@album.artists.first.id)
      =  " > #{@album.name.truncate(24)}"
  .row
    .col-lg-6.col-md-6.col-xs-6.album-show-left
      = set_image(@album,1,false,true)
      .album-info
        = @album.name.truncate(24)
        %br
        -# 評価機能
        - if user_signed_in?
          .album_rating
            = render "user/spotify/album_rating", album_rating: @album_rating, new_album_rating: @new_album_rating, album: @album
        -#　シェア機能
        -# Facebook
        #fb-root
        %script{async: "defer", crossorigin:"anonymous", src: "https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v8.0", nonce:"FfQIW2IJ"}
        .fb-share-button{"data-href" => "http://localhost:3000/user/spotify/album_show/#{@album.id};", "data-layout" => "button", "data-size" => "small"}
          %a.fb-xfbml-parse-ignore{target: "_blank", href: "https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A3000%2Fuser%2Fspotify%2Falbum_show%2F%23%7B%40album.id%7D&amp;src=sdkpreparse"}
        %br
        -# Line
        .line-it-button{"data-lang" => "ja", "data-type" => "share-a", "data-ver" => "3", "data-url" => "http://localhost:3000/user/spotify/album_show/#{@album.id}", "data-color" => "default", "data-size" => "small", "data-count" => "false", "style" => "display: none;"}
        %script{src: "https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js", async: "async", defer: "defer"}
        %br
        -# Twitter
        %a.twitter-share-button{href: "https://twitter.com/share?ref_src=twsrc%5Etfw","data-show-count" => "false"} Tweet
        %script{async: "defer", src: "https://platform.twitter.com/widgets.js", charset: "utf-8"}
    .col-lg-6.col-md-6.col-xs-6.album-show-right
      - if user_signed_in?
        -# コメント機能
        = form_with model: @album_comment,  url: user_album_comments_path(page: @page), class: "clearfix", local: true do |f|
          = render "layouts/error_message", model: f.object
          = f.text_area :comment, rows:"2",placeholder: "コメント"
          = f.hidden_field :album_id , :value => @album.id
          = f.submit "コメント", class: "btn btn-sm btn-base-1 mt-20 pull-right"
      - @album_comments.each do |comment|
        .row.comment
          .col-lg-1.col-md-1.col-xs-1
            = link_to user_user_path(comment.user) do
              = attachment_image_tag(comment.user, :profile_image,  size: "40x40", fallback: "no-image.png")
          .col-lg-2.col-md-2.col-xs-2.comment-user-name
            = link_to comment.user.user_name, user_user_path(comment.user)
          -# コメント更新用テキストボックス
          -if @comment == comment
            .col-lg-6.col-md-6.col-xs-6
              = form_with model: @comment, url: user_album_comment_path(comment, page: @page), local: true do |f|
                = render "layouts/error_message", model: f.object
                = f.text_area :comment, rows:"2", id: "album_comment#{comment.id}_edit_form"
                %br
                = link_to "取り消し", user_spotify_album_show_path(@comment.album_id, page: @page)
                = f.submit "更新する", class: "btn btn-sm btn-base-1 mt-20 pull-right"
          -else
            .col-lg-6.col-md-6.col-xs-6.comment-comment.table-responsive.text-center
              = comment.comment
          .col-lg-2.col-md-2.col-xs-2
            = comment.created_at.strftime('%Y/%m/%d')
          -# 編集/削除用プルダウン
          - if comment.user == current_user
            .col-lg-1.col-md-1.col-xs-1.fa.fa-bars.comment_pulldown
              %ul.comment_edit
                %li
                  = link_to user_spotify_album_show_path(@album.id, page: @page, comment_id: comment.id), id: "album_comment#{comment.id}_edit" do
                    %i.fa.fa-pencil
                %li
                  = link_to user_album_comment_path(comment), method: :delete, data: {confirm: "コメントを削除します"}, id: "album_comment#{comment.id}_delete" do
                    %i.fa.fa-trash-o
          - else
            .col-lg-1.col-md-1.col-xs-1
      %p= "#{AlbumComment.where(album_id: @album.id).count}コメント"
      - unless @error
        = paginate @album_comments
      -if @error
        = link_to "取り消し", user_spotify_album_show_path(@album.id, page: @page)
  .row
    .col-lg-12.col-md-12.col-xs-12.album-songs
      %table.table
        - @number = 0
        - @songs.each do |song|
          - @number += 1
          %tr
            %td
              = @number
            %td
              = link_to user_spotify_song_show_path(song.id) do
                = song.name.truncate(50)
            %td
              -# レビュー平均
              %p{{class: "star-rate-#{song.id}"}} 
                :javascript
                  $(".star-rate-#{song.id}").raty({
                    size: 36,
                    starOff: "#{asset_path('star-off.png')}",
                    starOn: "#{asset_path('star-on.png')}",
                    starHalf: "#{asset_path('star-half.png')}",
                    half: true,
                    readOnly: true,
                    score: "#{SongRating.where(song_id: song.id).average(:rate).to_f.round(1)}",
                  });
                = "(#{SongRating.where(song_id: song.id).average(:rate).to_f.round(1)})"
            %td
              %p= "#{SongComment.where(song_id: song.id).count}コメント"

app/views/user/spotify/song_show.html.haml
.container
  -# アーティストリンク>アルバムリンク>曲名
  .row
    %h2.head_title
      = link_to "#{@song.artists.first.name}", user_spotify_artist_show_path(@song.artists.first.id)
      > 
      =link_to "#{@song.album.name.truncate(24)}", user_spotify_album_show_path(@song.album.id)
      = " > #{@song.name.truncate(24)}"
  .row
    .col-lg-6.col-md-6.col-xs-6.song-show-left
      .song-image
        = set_image(@album,1,true,true)
        %br
        -# プレビューURL
        = link_to @song.preview_url do
          %i.fa.fa-play-circle Preview
        %br
        = link_to @song.external_urls["spotify"] do
          %i.fa.fa-spotify Listen on Spotify
        -# お気に入り
        .song_favorite
          = render "user/song_favorites/song_favorites", song_favorite: @song_favorite, song: @song
      .song-info
        - if @song.name.length <= 15
          %h4= @song.name
        -	elsif @song.name.length <= 20
          %h5= @song.name
        - else
          %h4.area
            .marquee= @song.name
        - if user_signed_in?
          -# 評価機能
          .song_rating
            = render "user/spotify/song_rating", song_rating: @song_rating, new_song_rating: @new_song_rating, song: @song
        -# シェア機能
        -# Facebook
        #fb-root
          %script{async: "defer", crossorigin: "anonymous", src: "https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v8.0", nonce: "q44w7xY2"}
        .fb-share-button{"data-href" => "http://localhost:3000/user/spotify/song_show/#{@song.id};", "data-layout" => "button", "data-size" => "small"}
          %a.fb-xfbml-parse-ignore{target: "_blank", href: "https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A3000%2Fuser%2Fspotify%2Fsong_show%2F%23%7B%40song.id%7D&amp;src=sdkpreparse"}
        %br
        -# Line
        .line-it-button{"data-lang" => "ja", "data-type" => "share-a", "data-ver" => "3", "data-url" => "http://localhost:3000/user/spotify/song_show/#{@song.id}", "data-color" => "default", "data-size" => "small", "data-count" => "false", "style" => "display: none;"}
          %script{src: "https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js", async: "async", defer: "defer"}
        %br
        -# Twitter
        %a.twitter-share-button{href: "https://twitter.com/share?ref_src=twsrc%5Etfw","data-show-count" => "false"} Tweet
        %script{async: "defer", src: "https://platform.twitter.com/widgets.js", charset: "utf-8"}
    .col-lg-6.col-md-6.col-xs-6.song-show-right
      - if user_signed_in?
        -# コメント機能
        = form_with model: @song_comment, url: user_song_comments_path(page: @page), class: "clearfix", local: true do |f|
          = render "layouts/error_message", model: f.object
          = f.text_area :comment, rows:"2",placeholder: "コメント"
          = f.hidden_field :song_id , :value => @song.id
          = f.submit "送信する", class: "btn btn-sm btn-base-1 mt-20 pull-right"
      - @song_comments.each do |comment|
        .row.comment
          .col-lg-1.col-md-1.col-xs-1
            = link_to user_user_path(comment.user) do
              = attachment_image_tag(comment.user, :profile_image,  size: "40x40", fallback: "no-image.png")
          .col-lg-2.col-md-2.col-xs-2.comment-user-name
            = link_to comment.user.user_name, user_user_path(comment.user)
          -# コメント更新用テキストボックス
          -if @comment == comment
            .col-lg-6.col-md-6.col-xs-6
              = form_with model: @comment, url: user_song_comment_path(comment, page: @page), local: true do |f|
                = render "layouts/error_message", model: f.object
                = f.text_area :comment, rows:"2", id: "song_comment#{comment.id}_edit_form"
                %br
                = link_to "取り消し", user_spotify_song_show_path(@comment.song_id, page: @page)
                = f.submit "更新する", class: "btn btn-sm btn-base-1 mt-20 pull-right"
          -else
            .col-lg-6.col-md-6.col-xs-6.comment-comment.table-responsive
              = comment.comment
          .col-lg-2.col-md-2.col-xs-2
            = comment.created_at.strftime('%Y/%m/%d')
          -# 編集/削除用プルダウン
          - if comment.user == current_user
            .col-lg-1.col-md-1.col-xs-1.fa.fa-bars.comment_pulldown
              %ul.comment_edit
                %li
                  = link_to user_spotify_song_show_path(@song.id, page: @page ,comment_id: comment.id), id: "song_comment#{comment.id}_edit" do
                    %i.fa.fa-pencil
                %li
                  = link_to user_song_comment_path(comment), method: :delete, data: {confirm: "コメントを削除します"}, id: "song_comment#{comment.id}_delete" do
                    %i.fa.fa-trash-o
          - else
            .col-lg-1.col-md-1.col-xs-1
      %p= "#{SongComment.where(song_id: @song.id).count}コメント"
      - unless @error
        = paginate @song_comments
      -if @error
        = link_to "取り消し", user_spotify_song_show_path(@song.id, page: @page)
      