config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  root to: 'user/home#top'

  namespace :user do
    get "home/top" => "home#top"
    get "home/about" => "home#about"
    resources :inquiry, only: [:index, :create]
    get  'inquiry/confirm' => 'inquiry#confirm'   
    get  'inquiry/thanks'  => 'inquiry#thanks'
    resources :users, only: [:show, :edit, :update]
    get "users/follow_index/:id" => "users#follow_index",as: "users_follow_index"
    get "users/follower_index/:id" => "users#follower_index",as: "users_follower_index"
    resources :relationships, only: [:create, :destroy]
    resources :messages, only: :create
    resources :rooms, only: [:create,:show]
    resources :spotify, only: :index
    get "spotify/artist_show/:id" => "spotify#artist_show" , as: "spotify_artist_show"
    get "spotify/album_show/:id" => "spotify#album_show" , as: "spotify_album_show"
    get "spotify/song_show/:id" => "spotify#song_show" , as: "spotify_song_show"
    get "spotify/new_releases" => "spotify#new_releases", as: "spotify_new_releases"
    get "spotify/charged_ups" => "spotify#charged_ups", as: "spotify_charged_ups"
    resources :artist_comments, only: [:create, :destroy, :update]
    resources :artist_ratings, only: [:create, :update]
    resources :album_comments, only: [:create, :destroy, :update]
    resources :album_ratings, only: [:create, :update]
    resources :song_comments, only: [:create, :destroy, :update]
    resources :song_ratings, only: [:create, :update]
    resources :song_favorites, only: [:index, :create, :destroy]
    resources :song_impressions, only: [:index]
    resources :notifications, only: :index
    resources :browsing_history, only: :index
  end

end

app/controllers/user/album_comments_controller.rb
class User::AlbumCommentsController < ApplicationController

  before_action :login_user_present?
  before_action :correct_comment_user, only: [:update, :destroy]
  before_action :set_page, except: [:destroy]

  def create
    @album_comment = current_user.album_comments.new(album_comment_params)
    @album_comment.album_id = params[:album_comment][:album_id]
    if @album_comment.save 
      redirect_to user_spotify_album_show_path(@album_comment.album_id, page: @page)
    else
      set_error_variables(@album_comment.album_id, params[:page])
    end
  end

  def update
    if @comment.update(album_comment_params)
      redirect_to user_spotify_album_show_path(@comment.album_id, page: @page)
    else
      @album_comment = AlbumComment.new
      set_error_variables(@comment.album_id, params[:page])
    end
  end

  def destroy
    @comment.destroy
    redirect_to user_spotify_album_show_path(@comment.album_id)
  end

  def set_error_variables(album_id, page_params)
    @album = RSpotify::Album.find(album_id)
    @songs = @album.tracks
    @album_comments = AlbumComment.where(album_id: @album.id).order("id DESC").page(page_params).per(5)
    if user_signed_in?
      @album_rating = current_user.album_ratings.find_by(album_id: @album.id)
      @new_album_rating = current_user.album_ratings.new
    end
    @error = true
    render "user/spotify/album_show"
  end

  private

  def album_comment_params
    params.require(:album_comment).permit(:comment)
  end
  

end

app/controllers/user/album_ratings_controller.rb
class User::AlbumRatingsController < ApplicationController

  before_action :correct_user, only: [:update]

  def create
    @album_rating = current_user.album_ratings.new(album_rating_params)
    @album_rating.album_id = params[:album_rating][:album_id]
    redirect_back(fallback_location: root_path) unless @album_rating.save
  end

  def update
    @album_rating = AlbumRating.find(params[:id])
    redirect_back(fallback_location: root_path) unless @album_rating.update(album_rating_params)
  end


  private

  def album_rating_params
    params.require(:album_rating).permit(:rate, :album_id)
  end

  def correct_user
    rating = AlbumRating.find(params[:id])
    redirect_to root_path unless current_user == rating.user
  end

end

app/controllers/user/artist_comments_controller.rb
class User::ArtistCommentsController < ApplicationController

  before_action :login_user_present?
  before_action :correct_comment_user, only: [:update, :destroy]
  before_action :set_page, except: [:destroy]

  def create
    @artist_comment = current_user.artist_comments.new(artist_comment_params)
    @artist_comment.artist_id = params[:artist_comment][:artist_id]
    if @artist_comment.save 
      redirect_to user_spotify_artist_show_path(@artist_comment.artist_id, page: @page)
    else
      set_error_variables(params[:artist_comment][:artist_id], params[:page])
    end
  end

  def update
    if @comment.update(artist_comment_params)
      redirect_to user_spotify_artist_show_path(@comment.artist_id, page: @page)
    else
      @artist_comment = ArtistComment.new
      set_error_variables(@comment.artist_id, params[:page])
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to user_spotify_artist_show_path(@comment.artist_id)
  end

  def set_error_variables(artist_id, page_params)
    @artist = RSpotify::Artist.find(artist_id)
    @albums = @artist.albums
    @artist_comments = ArtistComment.where(artist_id: @artist.id).order("id DESC").page(page_params).per(5)
    @error = true
    render "user/spotify/artist_show"
  end

  private

  def artist_comment_params
    params.require(:artist_comment).permit(:comment)
  end

end

app/controllers/user/artist_ratings_controller.rb
class User::ArtistRatingsController < ApplicationController

  before_action :correct_user, only: [:update]

  def create
    @artist_rating = current_user.artist_ratings.new(artist_rating_params)
    @artist_rating.artist_id = params[:artist_rating][:artist_id]
    redirect_back(fallback_location: root_path) unless @artist_rating.save
  end

  def update
    @artist_rating = ArtistRating.find(params[:id])
    redirect_back(fallback_location: root_path) unless @artist_rating.update(artist_rating_params)
  end


  private

  def artist_rating_params
    params.require(:artist_rating).permit(:rate, :artist_id)
  end

  def correct_user
    rating = ArtistRating.find(params[:id])
    redirect_to root_path unless current_user == rating.user
  end

end

app/controllers/user/browsing_history_controller.rb
class User::BrowsingHistoryController < ApplicationController

  def index
    @songs = SongImpression.where(user_id: current_user.id).order(updated_at: :desc).pluck(:song_id).uniq
  end

end

app/controllers/user/home_controller.rb
class User::HomeController < ApplicationController

  def top
    @song_comments = current_user.song_comments.order("id DESC").select(:song_id).distinct.limit(3) if current_user.present?
    @new_releases =  RSpotify::Album.new_releases
    @new_releases_in_jp =  RSpotify::Album.new_releases(country: 'JP')
    @charged_up = SongComment.group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
  end

  def about
    
  end

end

app/controllers/user/inquiry_controller.rb
class User::InquiryController < ApplicationController

  before_action :authenticate_user!

  def index
    @inquiry = (params[:inquiry] ? Inquiry.new(inquiry_params) : Inquiry.new )
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    render :index if @inquiry.invalid?
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      InquiryMailer.received_email(@inquiry).deliver
      InquiryMailer.confirm_email(@inquiry).deliver
      redirect_to user_inquiry_thanks_path
    else
      redirect_to user_inquiry_index_path
    end
  end

  def thanks
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
  
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  
  before_action :authenticate_user!

  def create

  end

end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController

  before_action :authenticate_user!

  def index
    #current_userの投稿に紐づいた通知一覧
    @notifications = current_user.passive_notifications.includes(:visiter)
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
      @notifications.where(checked: false).each do |notification|
        notification.update_attributes(checked: true)
      end
  end

end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController

  prepend_before_action :authenticate_user!
  before_action :set_user, :set_follows

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      @user.create_notification_follow!(current_user)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  private
  
  def set_user
    @user = User.find(params[:relationship][:follow_id])
  end

  def set_follows
    if params[:relationship][:index_user_id]
      @follows = User.find(params[:relationship][:index_user_id]).relationships
    end
  end

end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to user_room_path(@room.id, pair_user_id: @entry2.user_id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages.includes(:user)
      @pair_user = User.find(params[:pair_user_id])
      # フッター固定用
      @fixed_footer = true
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/user/song_comments_controller.rb
class User::SongCommentsController < ApplicationController

  before_action :login_user_present?
  before_action :correct_comment_user, only: [:update, :destroy]
  before_action :set_page, except: [:destroy]

  def create
    @song_comment = current_user.song_comments.new(song_comment_params)
    @song_comment.song_id = params[:song_comment][:song_id]
    if @song_comment.save 
      redirect_to user_spotify_song_show_path(@song_comment.song_id, page: @page)
    else
      set_error_variables(@song_comment.song_id, params[:page])
    end

  end

  def update
    if @comment.update(song_comment_params)
      redirect_to user_spotify_song_show_path(@comment.song_id, page: @page)
    else
      @song_comment = SongComment.new
      set_error_variables(@comment.song_id, params[:page])
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to user_spotify_song_show_path(@comment.song_id)
  end

  def set_error_variables(song_id, page_params)
    @song = RSpotify::Track.find(song_id)
    @album = @song.album
    @song_comments = SongComment.where(song_id: @song.id).order("id DESC").page(page_params).per(5)
    if user_signed_in?
      @song_rating = current_user.song_ratings.find_by(song_id: @song.id)
      @new_song_rating = current_user.song_ratings.new
    end
    @song_favorite = SongFavorite.find_by(user_id: current_user, song_id: @song.id)
    @error = true
    render "user/spotify/song_show"
  end

  private

  def song_comment_params
    params.require(:song_comment).permit(:comment)
  end

end

app/controllers/user/song_favorites_controller.rb
class User::SongFavoritesController < ApplicationController

  before_action :authenticate_user!, only: [:create]
  before_action :correct_user, only: [:destroy]
  before_action :set_song, only: [:create, :destroy]

  def index
    @user = User.find(params[:user_id])
    @song_favorites = @user.song_favorites
    # DM
    room_present?(@user)
  end


  def create
    new_song_favorite = current_user.song_favorites.new
    new_song_favorite.song_id = params[:song_id]
    new_song_favorite.save
    @song_favorite = SongFavorite.find_by(user_id: current_user, song_id: @song.id)
  end

  def destroy
    song_favorite = SongFavorite.find(params[:id])
    song_favorite.destroy
  end

  private

  def correct_user
    song_favorite = SongFavorite.find(params[:id])
    redirect_to root_path unless current_user == song_favorite.user
  end

  def set_song
    @song = RSpotify::Track.find(params[:song_id])
  end

end

app/controllers/user/song_impressions_controller.rb
class User::SongImpressionsController < ApplicationController

  def index
    case params[:times]
      when nil, "指定無し"
        @top_impressions = SongImpression.group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
      when "今日"
        @top_impressions = SongImpression.where(created_at: Time.zone.now.all_day).group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
        @time = "Today"
      when "１週間"
        @top_impressions = SongImpression.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day).group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
        @time = "Week"
      when "一ヶ月"
        @top_impressions = SongImpression.where(created_at: 1.month.ago.beginning_of_day..Time.zone.now.end_of_day).group(:song_id).count(:song_id).to_a.sort {|a,b| a[1] <=> b[1]}.reverse
        @time = "Month"
    end
  end
end

app/controllers/user/song_ratings_controller.rb
class User::SongRatingsController < ApplicationController

  before_action :correct_user, only: [:update]

  def create
    @song_rating = current_user.song_ratings.new(song_rating_params)
    @song_rating.song_id = params[:song_rating][:song_id]
    redirect_back(fallback_location: root_path) unless @song_rating.save
  end

  def update
    @song_rating = SongRating.find(params[:id])
    redirect_back(fallback_location: root_path) unless @song_rating.update(song_rating_params)
  end

  private

  def song_rating_params
    params.require(:song_rating).permit(:rate, :song_id)
  end

  def correct_user
    rating = SongRating.find(params[:id])
    redirect_to root_path unless current_user == rating.user
  end

end

app/controllers/user/spotify_controller.rb
class User::SpotifyController < ApplicationController

  before_action :set_page, only: [:artist_show, :album_show, :song_show]

  def index
    if params[:search].blank?
      redirect_back(fallback_location: root_path) 
    else
      @search_word = params[:search]
      @searchartists = RSpotify::Artist.search(@search_word)
      @searchalbums = RSpotify::Album.search(@search_word)
      @searchsongs = RSpotify::Track.search(@search_word)
      @artist_count = add_count(params[:artist_count])
      @album_count = add_count(params[:album_count])
      @song_count = add_count(params[:song_count])
    end
  end

  def artist_show
    @artist = RSpotify::Artist.find(params[:id])
    @albums = @artist.albums
    @artist_comment = ArtistComment.new
    @artist_comments = ArtistComment.includes(:user).where(artist_id: @artist.id).order("id DESC").page(params[:page]).per(5)
    @comment = ArtistComment.find(params[:comment_id]) if params[:comment_id].present?
  end

  def album_show
    @album = RSpotify::Album.find(params[:id])
    @songs = @album.tracks
    @album_comment = AlbumComment.new
    @album_comments = AlbumComment.includes(:user).where(album_id: @album.id).order("id DESC").page(params[:page]).per(5)
    @comment = AlbumComment.find(params[:comment_id]) if params[:comment_id].present?
    # 評価機能
    if user_signed_in?
      @album_rating = current_user.album_ratings.find_by(album_id: @album.id)
      @new_album_rating = current_user.album_ratings.new
    end
  end

  def song_show
    @song = RSpotify::Track.find(params[:id])
    @album = @song.album
    @song_comment = SongComment.new
    @song_comments = SongComment.includes(:user).where(song_id: @song.id).order("id DESC").page(params[:page]).per(5)
    @comment = SongComment.find(params[:comment_id]) if params[:comment_id].present?
    if user_signed_in?
      # 評価機能
      @song_rating = current_user.song_ratings.find_by(song_id: @song.id)
      @new_song_rating = current_user.song_ratings.new
      # PV機能
      current_user.create_song_impression(params[:id])
    end
    @song_favorite = SongFavorite.find_by(user_id: current_user, song_id: @song.id)
  end

  def new_releases
    @new_releases = new_releases_search(params[:country])
    @country_name = params[:country]
  end

  def charged_ups
    # 特定の期間内のコメントを取得して曲のIDの重複数が多い順に並び替えて取得
    @charged_up = sort_charged_ups(params[:times])[0]
    @time = sort_charged_ups(params[:times])[1]
  end
  
end

app/views/user/users/_follow_index.html.haml
%table.table
  - follows.each do |follow|
    %tr
      - user = follow.follow
      %td
        = attachment_image_tag(user, :profile_image,  size: "40x40", fallback: "no-image.png")
      %td
        = link_to user.user_name, user_user_path(user)
      %td
        - if user_signed_in?
          - unless current_user == user
            - if current_user.following?(user)
              = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }, url: user_relationship_path(user.id), remote: true) do |f|
                = f.hidden_field :follow_id, value: user.id
                = f.hidden_field :index_user_id, value: follow.user_id
                = f.submit 'フォロー中', class: 'follow-now btn btn-info'
            - else
              = form_for(current_user.relationships.build, url: user_relationships_path, remote: true) do |f|
                = f.hidden_field :follow_id, value: user.id
                = f.hidden_field :index_user_id, value: follow.user_id
                = f.submit 'フォロー', class: 'follows btn btn-outline-info'

app/views/user/users/_user_header.html.haml
.user-header.text-center 
  = link_to user_user_path(user) do
    %i.fa.fa-home
  = link_to user_song_favorites_path(user_id: user.id) do
    %i.fa.fa-bookmark
  - if user == current_user
    = link_to edit_user_user_path(user), id: "user-header-edit" do
      %i.fa.fa-pencil
    = link_to user_notifications_path, class: "user-notice" do
      %i.fa.fa-bell
      - if unchecked_notifications.any?
        %p.notice-count= @unchecked_notifications.count
  - unless user_signed_in? && user.id == current_user.id 
    - if (Relationship.find_by(user_id: user, follow_id: current_user)) && (current_user.following?(user)) 
      - if isRoom == true 
        = link_to user_room_path(roomId, pair_user_id: user, anchor: 'last') do
          %i.fa.fa-comments
      - else
        = form_for Room.new, url: user_rooms_path do |f|
          = fields_for Entry.new do |e|
            = e.hidden_field :user_id, value: user.id 
          = button_tag type: 'submit', class: "create_room" do
            %i.fa.fa-comments

app/views/user/users/edit.html.haml
= render "user/users/user_header", user: @user
.container.header-margin.edit-user-info
  %h2 User info
  = form_with model: @user ,url: user_user_path(@user),local: true do |f| 
    = render "layouts/error_message", model: f.object
    - if @user.email = 'guest@example.com'
      .error_message ゲストユーザーの編集はできません。
    = attachment_image_tag(@user, :profile_image,  size: "200x200", format: 'jpeg', fallback: "no-image.png", id: 'preview')
    .row
      .col-lg-2.col-md-2.col-xs-2.user_edit_label
        = f.label :user_name
        %br
        = f.label :image
        %br
        = f.label :introduction 
        = f.submit
      .col-lg-3.col-md-3.col-xs-3.user_edit_field
        = f.text_field :user_name, class: "name" 
        = f.attachment_field :profile_image, onchange: 'previewImage(preview)'
        = f.text_area :introduction, class: "introduction"

app/views/user/users/follow_index.html.haml
.container
  .row
    .col-lg-3.col-md-3.col-xs-3
    .col-lg-6.col-md-6.col-xs-6.follow_index
      - if @follows.present?
        = render "user/users/follow_index", follows: @follows, index_user: @user
      - else 
        ユーザーをフォローしていません

app/views/user/users/follower_index.html.haml
.container
  .row
    .col-lg-3.col-md-3.col-xs-3
    .col-lg-6.col-md-6.col-xs-6.follow_index
      - if @followers.present?
        %table.table
          - @followers.each do |follow|
            %tr
              - user = follow.user
              %td
                = attachment_image_tag(user, :profile_image,  size: "40x40", fallback: "no-image.png")
              %td
                = link_to user.user_name, user_user_path(user)
              %td
                %div{class: "follow_button#{user.id}"}
                  = render "user/relationships/follow_button", user: user
      - else
        フォロワーがいません

app/views/user/users/show.html.haml
= render "user/users/user_header", user: @user, isRoom: @isRoom, roomId: @roomId
.container.header-margin
  .row
    .col-lg-3.col-md-3.col-xs-3.user-show-user-image
      = attachment_image_tag(@user, :profile_image,  size: "200x200", fallback: "no-image.png")
    .col-lg-3.col-md-3.col-xs-3.relation-index
      .user-show-user-name= @user.user_name
      .user-show-user-introduction= @user.introduction
      - unless @user == current_user
        -# フォローボタン
        %div{class: "follow_button#{@user.id} follow_button"}
          = render "user/relationships/follow_button", user: @user
      .follow-follower #{link_to "フォロー", user_users_follow_index_path(@user)} | #{link_to "フォロワー", user_users_follower_index_path(@user)}
    .col-lg-6.col-md-6.col-xs-6.latest-chats
      -# 直近でDMを送ったユーザー一覧
      - if @user == current_user
        %h2 Latest Chats
        %table.table
          - @messages.each do |message|
            %tr
              - entry = Entry.where(room_id: message.room_id).where.not(user_id: current_user.id)
              - @chat_user = User.find(entry.first.user_id)
              %td
                = link_to user_user_path(@chat_user) do
                  = attachment_image_tag(@chat_user, :profile_image,  size: "25x25", fallback: "no-image.png")
              %td
                = @chat_user.user_name
              %td
                = link_to user_room_path(message.room_id, pair_user_id: @chat_user, anchor: 'last') do
                  %i.fa.fa-comments-o
  .row
    .col-lg-6.col-md-6.col-xs-6.latest-comment
      -# 直近でコメントした曲一覧
      - if user_signed_in? && @user == current_user
        %h2 Latest your comment
      - else
        %h2 Latest #{@user.user_name}'s comment
      - @song_comments.each do |song_comment|
        %table.table
          %tr
            %td
              - @song = RSpotify::Track.find(song_comment.song_id)
              = set_song_image(@song,2,true,false)
            %td
              = @song.name
    .col-lg-6.col-md-6.col-xs-6.user-favorites
      -# お気に入り(ブックマーク)曲一覧
      - if user_signed_in? && @user == current_user
        %h2.favorite your favorite
      - else
        %h2.favorite #{@user.user_name}'s favorite
      = link_to "View All", user_song_favorites_path(user_id: @user.id),class: "viewall"
      - @song_favorites.each do |song_favorite|
        %table.table
          %tr
            %td
              - @song = RSpotify::Track.find(song_favorite.song_id)
              = set_song_image(@song,2,true,false)
            %td
              = @song.name